---
- hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: install or update via yum
      yum:
        name={{ item }}
        state=installed
        update_cache=yes
      with_items:
        - mysql-server
        - tomcat
        - nginx
    - name: restart service
      service:
          name={{ item }}
          state=restarted
      with_items:
        - mysqld
        - tomcat
        - nginx
