---
- hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: install or update via yum
      yum:
        pkg={{ item }}
        state=installed
        update_cache=yes
      with_items:
        - mysql-server
        # TODO yum install できないので
        #- tomcat7
        - nginx
    - service: name=mysqld state=restarted
    - service: name=nginx state=restarted
